import type { AppState, AuthUser, ChatMessage, Exercise, Member, TrainingProgram, WorkoutLog } from "./types";
import { formatDateDdMmYyyy } from "./dateFormat";

export const MOTUS = {
  turquoise: "#30e3be",
  pink: "#d91278",
  acid: "#daff01",
  paleMint: "#d6fbf1",
  ink: "#0f172a",
};

export const STORAGE_KEY = "motus_pt_app_v2";

export const demoUsers: Array<AuthUser & { password: string }> = [
  { id: "u1", role: "trainer", name: "Motus PT", email: "trainer@motus.no", password: "123456" },
  { id: "u2", role: "member", name: "Emma Hansen", email: "emma@example.com", password: "123456", memberId: "m1" },
  { id: "u3", role: "member", name: "Martin Johansen", email: "martin@example.com", password: "123456", memberId: "m2" },
];

const initialMembers: Member[] = [
  {
    id: "m1",
    name: "Emma Hansen",
    email: "emma@example.com",
    isActive: true,
    invitedAt: "",
    phone: "900 11 111",
    birthDate: "1991-06-14",
    weight: "72",
    height: "168",
    level: "Litt øvet",
    membershipType: "Premium",
    customerType: "PT-kunde",
    daysSinceActivity: "1",
    goal: "Bli sterkere i hele kroppen",
    focus: "Helkroppsstyrke og trygg progresjon",
    personalGoals: "Bli sterkere, få mer energi og trene jevnt gjennom uka.",
    injuries: "Ingen registrerte skader",
    coachNotes: "Svarte godt på første program.",
  },
  {
    id: "m2",
    name: "Martin Johansen",
    email: "martin@example.com",
    isActive: true,
    invitedAt: "",
    phone: "900 22 222",
    birthDate: "1984-03-05",
    weight: "96",
    height: "182",
    level: "Nybegynner",
    membershipType: "Standard",
    customerType: "Oppfølging",
    daysSinceActivity: "9",
    goal: "Gå ned i fettprosent",
    focus: "Vaner og jevn aktivitet",
    personalGoals: "Få bedre kondisjon og komme inn i faste rutiner.",
    injuries: "Stiv hofte ved mye løping",
    coachNotes: "Trenger enkel og tydelig struktur.",
  },
];

const initialExercises: Exercise[] = [
  { id: "e1", name: "Knebøy", category: "Styrke", group: "Bein", equipment: "Stang", level: "Litt øvet", description: "Hold brystet oppe, spenn kjernen og gå kontrollert ned til minst parallell." },
  { id: "e2", name: "Frontbøy", category: "Styrke", group: "Bein", equipment: "Stang", level: "Øvet", description: "Albuer høyt og stangen hvilende foran skuldrene gjennom hele løftet." },
  { id: "e3", name: "Rumensk markløft", category: "Styrke", group: "Bakside lår", equipment: "Stang", level: "Litt øvet", description: "Skyv hoften bakover med lett bøy i knærne og hold ryggen nøytral." },
  { id: "e4", name: "Markløft", category: "Styrke", group: "Rygg", equipment: "Stang", level: "Øvet", description: "Press føttene i gulvet og løft stangen tett inntil kroppen." },
  { id: "e5", name: "Beinpress", category: "Styrke", group: "Bein", equipment: "Maskin", level: "Nybegynner", description: "Hold korsryggen i setet og press jevnt gjennom hele foten." },
  { id: "e6", name: "Utfall bakover", category: "Styrke", group: "Bein", equipment: "Manualer", level: "Nybegynner", description: "Ta et langt steg bak, senk kneet kontrollert og press opp igjen." },
  { id: "e7", name: "Bulgarian split squat", category: "Styrke", group: "Bein", equipment: "Manualer", level: "Litt øvet", description: "Bakre fot på benk, hold overkroppen stabil og jobb dypt i fremre bein." },
  { id: "e8", name: "Hip thrust", category: "Styrke", group: "Sete", equipment: "Stang", level: "Litt øvet", description: "Posterior tilt i toppen og press hoften helt opp med kontrollert tempo." },
  { id: "e9", name: "Leg curl", category: "Styrke", group: "Bakside lår", equipment: "Maskin", level: "Nybegynner", description: "Trekk hælene mot setet uten å løfte hoften fra puten." },
  { id: "e10", name: "Leg extension", category: "Styrke", group: "Forside lår", equipment: "Maskin", level: "Nybegynner", description: "Spark ut kontrollert og hold et kort stopp i topposisjon." },
  { id: "e11", name: "Benkpress", category: "Styrke", group: "Bryst", equipment: "Stang", level: "Litt øvet", description: "Skuldre bak/ned, lett svai i ryggen og stangen mot nedre bryst." },
  { id: "e12", name: "Skrå manualpress", category: "Styrke", group: "Bryst", equipment: "Manualer", level: "Nybegynner", description: "Hold håndledd stabile og press manualene i en myk bue oppover." },
  { id: "e13", name: "Push-up", category: "Styrke", group: "Bryst", equipment: "Kroppsvekt", level: "Nybegynner", description: "Kroppen i en rett linje, albuer cirka 45 grader fra overkroppen." },
  { id: "e14", name: "Dips i stativ", category: "Styrke", group: "Bryst/Triceps", equipment: "Kroppsvekt", level: "Litt øvet", description: "Senk kontrollert med brystet frem, press opp uten å overstrekk albuene." },
  { id: "e15", name: "Flyes i kabel", category: "Styrke", group: "Bryst", equipment: "Kabel", level: "Nybegynner", description: "Myke albuer, klem brystet sammen foran kroppen i sluttfasen." },
  { id: "e16", name: "Skulderpress", category: "Styrke", group: "Skuldre", equipment: "Manualer", level: "Nybegynner", description: "Press vertikalt over hodet uten å svaie korsryggen." },
  { id: "e17", name: "Arnold press", category: "Styrke", group: "Skuldre", equipment: "Manualer", level: "Litt øvet", description: "Roter manualene kontrollert fra front til overhead i presset." },
  { id: "e18", name: "Sidehev", category: "Styrke", group: "Skuldre", equipment: "Manualer", level: "Nybegynner", description: "Løft til skulderhøyde med lett bøy i albuen og rolig senkefase." },
  { id: "e19", name: "Face pull", category: "Styrke", group: "Øvre rygg", equipment: "Kabel", level: "Nybegynner", description: "Trekk tau mot ansiktet og roter ut i skuldrene i toppen." },
  { id: "e20", name: "Nedtrekk bredt grep", category: "Styrke", group: "Rygg", equipment: "Kabel", level: "Nybegynner", description: "Start med skulderbladene ned og trekk stangen mot øvre bryst." },
  { id: "e21", name: "Sittende roing", category: "Styrke", group: "Rygg", equipment: "Kabel", level: "Nybegynner", description: "Trekk albuer bakover og hold brystet høyt gjennom repetisjonen." },
  { id: "e22", name: "Enarms roing", category: "Styrke", group: "Rygg", equipment: "Manual", level: "Nybegynner", description: "Stabiliser med motsatt hånd på benk og trekk albuen mot hoften." },
  { id: "e23", name: "Pull-up", category: "Styrke", group: "Rygg", equipment: "Kroppsvekt", level: "Øvet", description: "Trekk brystet opp mot stangen med kontrollert senkefase." },
  { id: "e24", name: "Omvendt flyes", category: "Styrke", group: "Bakside skulder", equipment: "Manualer", level: "Nybegynner", description: "Len deg frem, hold lett bøy i albuer og spre armene ut til siden." },
  { id: "e25", name: "Bicepscurl", category: "Styrke", group: "Biceps", equipment: "Manualer", level: "Nybegynner", description: "Albuer tett inntil kroppen og full kontroll på vei ned." },
  { id: "e26", name: "Hammercurl", category: "Styrke", group: "Biceps", equipment: "Manualer", level: "Nybegynner", description: "Nøytralt grep gjennom hele løftet for ekstra underarmsaktivering." },
  { id: "e27", name: "Triceps pushdown", category: "Styrke", group: "Triceps", equipment: "Kabel", level: "Nybegynner", description: "Hold overarmene rolig og press ned til full albueekstensjon." },
  { id: "e28", name: "Franskpress", category: "Styrke", group: "Triceps", equipment: "EZ-stang", level: "Litt øvet", description: "Senk vekten bak hodet med stabile albuer før du presser opp." },
  { id: "e29", name: "Planke", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Spenn sete og mage slik at kroppen holdes helt rett." },
  { id: "e30", name: "Dead bug", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Hold korsryggen i gulvet mens motsatt arm og bein strekkes ut." },
  { id: "e31", name: "Pallof press", category: "Styrke", group: "Kjerne", equipment: "Kabel", level: "Nybegynner", description: "Press håndtaket rett ut og motstå rotasjon i overkroppen." },
  { id: "e32", name: "Russian twist", category: "Styrke", group: "Kjerne", equipment: "Kettlebell", level: "Litt øvet", description: "Roter rolig side til side med aktiv kjernespenn hele tiden." },
  { id: "e33", name: "Mølle intervall løp", category: "Kondisjon", group: "Kondisjon", equipment: "Tredemølle", level: "Litt øvet", description: "Veksle mellom korte drag med høy fart og rolig aktiv pause." },
  { id: "e34", name: "Sykling intervall", category: "Kondisjon", group: "Kondisjon", equipment: "Spinningsykkel", level: "Nybegynner", description: "Arbeid i intervaller med jevn kadens og tydelig motstandsjustering." },
  { id: "e35", name: "Romaskin intervall", category: "Kondisjon", group: "Kondisjon", equipment: "Romaskin", level: "Nybegynner", description: "Skyv kraftfullt med beina først, deretter rygg og armer." },
  { id: "e36", name: "Airbike sprint", category: "Kondisjon", group: "Kondisjon", equipment: "Airbike", level: "Litt øvet", description: "Korte, harde spurter med full innsats og kontrollert hvile." },
  { id: "e37", name: "Burpees", category: "Kondisjon", group: "Helkropp", equipment: "Kroppsvekt", level: "Litt øvet", description: "Hold tempoet jevnt og land mykt for å beskytte knær og ankler." },
  { id: "e38", name: "Jumping jacks", category: "Kondisjon", group: "Helkropp", equipment: "Kroppsvekt", level: "Nybegynner", description: "Rytmisk helkroppsbevegelse med aktiv bruk av armene." },
  { id: "e39", name: "Mountain climbers", category: "Kondisjon", group: "Kjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Trekk knærne raskt mot brystet mens skuldrene holdes over hendene." },
  { id: "e40", name: "Hoppetau", category: "Kondisjon", group: "Kondisjon", equipment: "Hoppetau", level: "Nybegynner", description: "Små, effektive hopp med lav belastning og jevn rytme." },
  { id: "e41", name: "Step-up med høy puls", category: "Kondisjon", group: "Bein", equipment: "Benk", level: "Nybegynner", description: "Bytt fot kontinuerlig og jobb i jevnt tempo for å heve pulsen." },
  { id: "e42", name: "Kettlebell swing", category: "Kondisjon", group: "Bakside kjede", equipment: "Kettlebell", level: "Litt øvet", description: "Hofteleddsdrevet bevegelse, ikke løft med armene." },
  { id: "e43", name: "Sled push", category: "Kondisjon", group: "Helkropp", equipment: "Slede", level: "Litt øvet", description: "Stabil overkropp, korte kraftfulle steg og jevn fremdrift." },
  { id: "e44", name: "Boksing intervall", category: "Kondisjon", group: "Kondisjon", equipment: "Boksesekk", level: "Nybegynner", description: "Kombiner slagserier med fotarbeid i tidsstyrte runder." },
  { id: "e45", name: "Nedjogg", category: "Kondisjon", group: "Restitusjon", equipment: "Tredemølle", level: "Nybegynner", description: "Rolig tempo for å senke puls gradvis etter harde intervaller." },
  { id: "e46", name: "Hoftebøyer-strekk", category: "Uttøyning", group: "Hofte", equipment: "Kroppsvekt", level: "Nybegynner", description: "Skyv hoften rolig frem til du kjenner strekk foran hoften." },
  { id: "e47", name: "Hamstring-strekk", category: "Uttøyning", group: "Bakside lår", equipment: "Kroppsvekt", level: "Nybegynner", description: "Hold lang rygg og strekk baksiden av låret uten å runde korsryggen." },
  { id: "e48", name: "Quadriceps-strekk", category: "Uttøyning", group: "Forside lår", equipment: "Kroppsvekt", level: "Nybegynner", description: "Trekk hælen mot setet og hold knærne samlet." },
  { id: "e49", name: "Setestrekk liggende", category: "Uttøyning", group: "Sete", equipment: "Kroppsvekt", level: "Nybegynner", description: "Kryss ankelen over motsatt kne og trekk rolig inn mot brystet." },
  { id: "e50", name: "Bryståpner mot vegg", category: "Uttøyning", group: "Bryst", equipment: "Vegg", level: "Nybegynner", description: "Plasser armen på veggen og roter kroppen forsiktig bort." },
  { id: "e51", name: "Lats-strekk", category: "Uttøyning", group: "Rygg", equipment: "Strikk", level: "Nybegynner", description: "Len deg bakover med strake armer for å åpne siden av ryggen." },
  { id: "e52", name: "Katt-ku mobilitet", category: "Uttøyning", group: "Rygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Veksle mellom fleksjon og ekstensjon i ryggen i rolig tempo." },
  { id: "e53", name: "Child's pose", category: "Uttøyning", group: "Rygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Sitt bak på hælene og strekk armene frem for avspenning i rygg/skuldre." },
  { id: "e54", name: "Sittende rotasjon", category: "Uttøyning", group: "Brystrygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Roter rolig i overkroppen mens hoftene holdes stabile." },
  { id: "e55", name: "Leggstrekk mot vegg", category: "Uttøyning", group: "Legg", equipment: "Vegg", level: "Nybegynner", description: "Hold hælen i gulvet og len kroppen frem til du kjenner strekk i leggen." },
  { id: "e56", name: "Hack squat", category: "Styrke", group: "Bein", equipment: "Maskin", level: "Litt øvet", description: "Hold korsrygg mot puten og press jevnt gjennom hele foten." },
  { id: "e57", name: "Goblet squat", category: "Styrke", group: "Bein", equipment: "Kettlebell", level: "Nybegynner", description: "Hold vekten tett mot brystet og jobb med stabil overkropp." },
  { id: "e58", name: "Gående utfall", category: "Styrke", group: "Bein", equipment: "Manualer", level: "Litt øvet", description: "Ta lange kontrollerte steg og hold hoften stabil hele veien." },
  { id: "e59", name: "Step-up med manualer", category: "Styrke", group: "Bein", equipment: "Manualer", level: "Nybegynner", description: "Press gjennom fremre fot og kontroller senkefasen tilbake." },
  { id: "e60", name: "Glute bridge", category: "Styrke", group: "Sete", equipment: "Kroppsvekt", level: "Nybegynner", description: "Klem setet i toppen og unngå overstrekk i korsryggen." },
  { id: "e61", name: "Kabel pull-through", category: "Styrke", group: "Bakside kjede", equipment: "Kabel", level: "Litt øvet", description: "Skyv hoften frem med nøytral rygg i hele bevegelsen." },
  { id: "e62", name: "Sumo markløft", category: "Styrke", group: "Bakside kjede", equipment: "Stang", level: "Øvet", description: "Bred fotstilling og knær i samme retning som tær." },
  { id: "e63", name: "Good morning", category: "Styrke", group: "Bakside lår", equipment: "Stang", level: "Øvet", description: "Start lett og hold sterk kjernespenn gjennom hele løftet." },
  { id: "e64", name: "Nordic hamstring curl", category: "Styrke", group: "Bakside lår", equipment: "Kroppsvekt", level: "Øvet", description: "Brems eksentrisk så langt du klarer med kontroll." },
  { id: "e65", name: "Sittende tåhev", category: "Styrke", group: "Legg", equipment: "Maskin", level: "Nybegynner", description: "Full bevegelsesbane med rolig stopp i topp og bunn." },
  { id: "e66", name: "Stående tåhev", category: "Styrke", group: "Legg", equipment: "Maskin", level: "Nybegynner", description: "Hold trykket over stortåballen og unngå å falle inn i ankelen." },
  { id: "e67", name: "Smal benkpress", category: "Styrke", group: "Bryst/Triceps", equipment: "Stang", level: "Litt øvet", description: "Hold albuene kontrollert nær kroppen gjennom løftet." },
  { id: "e68", name: "Decline benkpress", category: "Styrke", group: "Bryst", equipment: "Stang", level: "Øvet", description: "Stabil skulderposisjon og jevn bue på stangbanen." },
  { id: "e69", name: "Maskin brystpress", category: "Styrke", group: "Bryst", equipment: "Maskin", level: "Nybegynner", description: "Jevnt tempo og full kontroll i ytterstilling." },
  { id: "e70", name: "Pec deck", category: "Styrke", group: "Bryst", equipment: "Maskin", level: "Nybegynner", description: "Hold brystet oppe og klem sammen i midten." },
  { id: "e71", name: "Landmine press", category: "Styrke", group: "Skuldre", equipment: "Landmine", level: "Litt øvet", description: "Press i diagonal bane med stabil kjernespenn." },
  { id: "e72", name: "Push press", category: "Styrke", group: "Skuldre", equipment: "Stang", level: "Øvet", description: "Kort dip i knær før eksplosivt press over hodet." },
  { id: "e73", name: "Omvendt pec deck", category: "Styrke", group: "Bakside skulder", equipment: "Maskin", level: "Nybegynner", description: "Trekk skulderbladene sammen uten å løfte skuldrene." },
  { id: "e74", name: "Scaption raise", category: "Styrke", group: "Skuldre", equipment: "Manualer", level: "Nybegynner", description: "Løft i scapulaplan med lett bøy i albuer." },
  { id: "e75", name: "Shrugs", category: "Styrke", group: "Øvre rygg", equipment: "Manualer", level: "Nybegynner", description: "Løft skuldrene rett opp og senk kontrollert." },
  { id: "e76", name: "Rack pull", category: "Styrke", group: "Rygg", equipment: "Stang", level: "Øvet", description: "Start fra rack-høyde og hold stangen tett mot kroppen." },
  { id: "e77", name: "T-bar roing", category: "Styrke", group: "Rygg", equipment: "Maskin", level: "Litt øvet", description: "Trekk albuene bakover med stolt bryst." },
  { id: "e78", name: "Chest-supported row", category: "Styrke", group: "Rygg", equipment: "Maskin", level: "Nybegynner", description: "La brystputen avlaste korsrygg og fokuser på ryggarbeid." },
  { id: "e79", name: "Smal nedtrekk", category: "Styrke", group: "Rygg", equipment: "Kabel", level: "Nybegynner", description: "Trekk håndtaket mot øvre bryst med kontroll." },
  { id: "e80", name: "Straight-arm pulldown", category: "Styrke", group: "Rygg", equipment: "Kabel", level: "Nybegynner", description: "Hold armene nesten strake og press ned med latene." },
  { id: "e81", name: "Inverted row", category: "Styrke", group: "Rygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Hold kroppen strak og trekk brystet mot stangen." },
  { id: "e82", name: "Preacher curl", category: "Styrke", group: "Biceps", equipment: "EZ-stang", level: "Litt øvet", description: "Kontrollert tempo med full strekk i bunn." },
  { id: "e83", name: "Kabelcurl", category: "Styrke", group: "Biceps", equipment: "Kabel", level: "Nybegynner", description: "Hold albuene stabile og spenn i toppen." },
  { id: "e84", name: "Konsentrasjonscurl", category: "Styrke", group: "Biceps", equipment: "Manual", level: "Nybegynner", description: "Lås albuen mot innsiden av låret for ren bicepsjobb." },
  { id: "e85", name: "Overhead triceps extension", category: "Styrke", group: "Triceps", equipment: "Manual", level: "Nybegynner", description: "Hold albuene samlet og kontroller dybden bak hodet." },
  { id: "e86", name: "Kickback", category: "Styrke", group: "Triceps", equipment: "Manual", level: "Nybegynner", description: "Stabil overkropp og full strekk bakover i albuen." },
  { id: "e87", name: "Cable rope overhead extension", category: "Styrke", group: "Triceps", equipment: "Kabel", level: "Litt øvet", description: "Trekk tauet fra bak hodet til full strekk over kroppen." },
  { id: "e88", name: "Hanging knee raise", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Litt øvet", description: "Unngå sving, trekk knærne kontrollert opp mot brystet." },
  { id: "e89", name: "Ab wheel rollout", category: "Styrke", group: "Kjerne", equipment: "Ab wheel", level: "Øvet", description: "Hold hoften stabil og unngå svai i korsrygg." },
  { id: "e90", name: "Cable woodchopper", category: "Styrke", group: "Kjerne", equipment: "Kabel", level: "Litt øvet", description: "Roter gjennom overkroppen med kontrollert tempo." },
  { id: "e91", name: "Farmer's walk", category: "Styrke", group: "Grepsstyrke", equipment: "Manualer", level: "Litt øvet", description: "Gå med stolt holdning og jevn kjernespenn." },
  { id: "e92", name: "Suitcase carry", category: "Styrke", group: "Kjerne", equipment: "Kettlebell", level: "Litt øvet", description: "Bær vekt på en side og motstå sidebøy i overkropp." },
  { id: "e93", name: "Sled drag bakover", category: "Styrke", group: "Bein", equipment: "Slede", level: "Litt øvet", description: "Korte, kontrollerte steg med jevnt drag i sleden." },
  { id: "e94", name: "Smith split squat", category: "Styrke", group: "Bein", equipment: "Smith-maskin", level: "Nybegynner", description: "Stabil bane og kontrollert dybde i fremre bein." },
  { id: "e95", name: "Maskin roing en-arm", category: "Styrke", group: "Rygg", equipment: "Maskin", level: "Nybegynner", description: "Jobb side for side med fokus på skulderbladskontroll." },
  { id: "e96", name: "Zercher squat", category: "Styrke", group: "Bein", equipment: "Stang", level: "Øvet", description: "Hold stangen stabil i albuekroken og hold brystet oppe." },
  { id: "e97", name: "Box squat", category: "Styrke", group: "Bein", equipment: "Stang", level: "Litt øvet", description: "Sett deg kontrollert til boks og reis deg eksplosivt opp." },
  { id: "e98", name: "Pausebøy", category: "Styrke", group: "Bein", equipment: "Stang", level: "Øvet", description: "Stopp et sekund i bunn for mer kontroll og styrke." },
  { id: "e99", name: "Båndet knebøy", category: "Styrke", group: "Bein", equipment: "Strikk", level: "Nybegynner", description: "Press knær ut mot strikken gjennom hele bevegelsen." },
  { id: "e100", name: "Curtsy lunge", category: "Styrke", group: "Sete", equipment: "Manualer", level: "Nybegynner", description: "Kryss bakover i utfall og hold hoften stabil." },
  { id: "e101", name: "Cossack squat", category: "Styrke", group: "Bein", equipment: "Kroppsvekt", level: "Litt øvet", description: "Flytt vekten sideveis med god kontroll i hoftene." },
  { id: "e102", name: "Single-leg hip thrust", category: "Styrke", group: "Sete", equipment: "Kroppsvekt", level: "Litt øvet", description: "Press opp med ett bein og hold hoften rett." },
  { id: "e103", name: "Frog pumps", category: "Styrke", group: "Sete", equipment: "Kroppsvekt", level: "Nybegynner", description: "Klem setet hardt i topp med føttene samlet." },
  { id: "e104", name: "B-stance rumensk markløft", category: "Styrke", group: "Bakside lår", equipment: "Manualer", level: "Litt øvet", description: "Hovedbelastning på fremre bein med stabil hofte." },
  { id: "e105", name: "Stiff-leg deadlift", category: "Styrke", group: "Bakside lår", equipment: "Stang", level: "Litt øvet", description: "Hold beina nesten strake og ryggen nøytral." },
  { id: "e106", name: "Deficit markløft", category: "Styrke", group: "Bakside kjede", equipment: "Stang", level: "Øvet", description: "Start fra lavere posisjon for økt bevegelsesutslag." },
  { id: "e107", name: "Roman chair back extension", category: "Styrke", group: "Rygg", equipment: "Roman chair", level: "Nybegynner", description: "Hold kjernen aktiv og løft kontrollert opp." },
  { id: "e108", name: "Cable kickback sete", category: "Styrke", group: "Sete", equipment: "Kabel", level: "Nybegynner", description: "Skyv hælen bakover uten å svaie korsryggen." },
  { id: "e109", name: "Abduksjon maskin", category: "Styrke", group: "Sete", equipment: "Maskin", level: "Nybegynner", description: "Press knær ut med rolig tempo og kontrollert retur." },
  { id: "e110", name: "Adduksjon maskin", category: "Styrke", group: "Innside lår", equipment: "Maskin", level: "Nybegynner", description: "Trekk bena sammen kontrollert gjennom hele løftet." },
  { id: "e111", name: "Tibialis raise", category: "Styrke", group: "Legg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Løft tærne opp og styrk framsiden av leggen." },
  { id: "e112", name: "Donkey calf raise", category: "Styrke", group: "Legg", equipment: "Maskin", level: "Litt øvet", description: "Press opp med full strekk i ankelleddet." },
  { id: "e113", name: "Floor press", category: "Styrke", group: "Bryst/Triceps", equipment: "Manualer", level: "Nybegynner", description: "Press fra gulv med stabil skulderposisjon." },
  { id: "e114", name: "Spoto press", category: "Styrke", group: "Bryst", equipment: "Stang", level: "Øvet", description: "Stopp stangen rett over brystet før press opp." },
  { id: "e115", name: "Push-up smalt grep", category: "Styrke", group: "Triceps", equipment: "Kroppsvekt", level: "Nybegynner", description: "Hold albuene tett for mer tricepsaktivering." },
  { id: "e116", name: "Ring push-up", category: "Styrke", group: "Bryst", equipment: "Ringer", level: "Litt øvet", description: "Stabiliser skuldrene mens du presser opp." },
  { id: "e117", name: "Enarms kabelpress", category: "Styrke", group: "Bryst", equipment: "Kabel", level: "Litt øvet", description: "Press frem uten rotasjon i overkroppen." },
  { id: "e118", name: "Dumbbell pullover", category: "Styrke", group: "Bryst/Rygg", equipment: "Manual", level: "Litt øvet", description: "Senk kontrollert bak hodet og trekk tilbake." },
  { id: "e119", name: "Sittende militærpress", category: "Styrke", group: "Skuldre", equipment: "Stang", level: "Litt øvet", description: "Sitt stabilt og press stangen vertikalt." },
  { id: "e120", name: "Enarms skulderpress", category: "Styrke", group: "Skuldre", equipment: "Manual", level: "Nybegynner", description: "Hold kjernen stram og press kontrollert." },
  { id: "e121", name: "Y-raise på benk", category: "Styrke", group: "Skuldre", equipment: "Manualer", level: "Nybegynner", description: "Løft armene i Y-form med fokus på bakside skulder." },
  { id: "e122", name: "W-raise med strikk", category: "Styrke", group: "Bakside skulder", equipment: "Strikk", level: "Nybegynner", description: "Trekk albuene bak og roter ut i toppen." },
  { id: "e123", name: "Enarms lat pulldown", category: "Styrke", group: "Rygg", equipment: "Kabel", level: "Nybegynner", description: "Trekk albuen ned mot hoften med kontroll." },
  { id: "e124", name: "Meadows row", category: "Styrke", group: "Rygg", equipment: "Landmine", level: "Øvet", description: "Trekk i diagonal bane og hold hofte stabil." },
  { id: "e125", name: "Seal row", category: "Styrke", group: "Rygg", equipment: "Stang", level: "Litt øvet", description: "Roing fra benk med null hjelp fra korsrygg." },
  { id: "e126", name: "Pendlay row", category: "Styrke", group: "Rygg", equipment: "Stang", level: "Øvet", description: "Start hver repetisjon fra gulvet med eksplosiv roing." },
  { id: "e127", name: "Kroppsvekt roing i ringer", category: "Styrke", group: "Rygg", equipment: "Ringer", level: "Nybegynner", description: "Hold kroppen strak og trekk brystet opp." },
  { id: "e128", name: "Reverse-grip row", category: "Styrke", group: "Rygg", equipment: "Stang", level: "Litt øvet", description: "Underhåndsgrep for ekstra bicepsarbeid." },
  { id: "e129", name: "Cable row bredt grep", category: "Styrke", group: "Rygg", equipment: "Kabel", level: "Nybegynner", description: "Trekk bredt og klem skulderbladene sammen." },
  { id: "e130", name: "Bayesian curl", category: "Styrke", group: "Biceps", equipment: "Kabel", level: "Litt øvet", description: "Stå fremoverlent fra kabel for konstant spenning." },
  { id: "e131", name: "Drag curl", category: "Styrke", group: "Biceps", equipment: "Stang", level: "Litt øvet", description: "Trekk stangen tett opp langs kroppen." },
  { id: "e132", name: "Zottman curl", category: "Styrke", group: "Biceps/Underarm", equipment: "Manualer", level: "Litt øvet", description: "Supiner opp, proner ned for ekstra underarm." },
  { id: "e133", name: "Omvendt curl", category: "Styrke", group: "Underarm", equipment: "EZ-stang", level: "Nybegynner", description: "Overhåndsgrep med kontrollert tempo." },
  { id: "e134", name: "Wrist curl", category: "Styrke", group: "Underarm", equipment: "Manualer", level: "Nybegynner", description: "Fokuser på håndleddsbevegelse med lett vekt." },
  { id: "e135", name: "Reverse wrist curl", category: "Styrke", group: "Underarm", equipment: "Manualer", level: "Nybegynner", description: "Løft håndryggen opp med kontrollert retur." },
  { id: "e136", name: "Skull crusher", category: "Styrke", group: "Triceps", equipment: "EZ-stang", level: "Litt øvet", description: "Senk stangen mot pannen med stabile albuer." },
  { id: "e137", name: "JM press", category: "Styrke", group: "Triceps", equipment: "Stang", level: "Øvet", description: "Kombiner smal press og tricepsfokus i samme bane." },
  { id: "e138", name: "Triceps dip benk", category: "Styrke", group: "Triceps", equipment: "Benk", level: "Nybegynner", description: "Senk kontrollert og press opp med triceps." },
  { id: "e139", name: "Kabel triceps kickback", category: "Styrke", group: "Triceps", equipment: "Kabel", level: "Nybegynner", description: "Hold overarm stabil og strekk bakover." },
  { id: "e140", name: "Diamond push-up", category: "Styrke", group: "Triceps", equipment: "Kroppsvekt", level: "Litt øvet", description: "Smalt håndgrep under brystet for triceps." },
  { id: "e141", name: "Hollow hold", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Litt øvet", description: "Hold korsrygg i gulv med strake armer og ben." },
  { id: "e142", name: "V-ups", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Litt øvet", description: "Løft overkropp og ben samtidig i V-posisjon." },
  { id: "e143", name: "Toe touches", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Rekk mot tærne med kontrollert kjernespenn." },
  { id: "e144", name: "Sideplanke med hoftehev", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Litt øvet", description: "Løft og senk hoften med stabil linje." },
  { id: "e145", name: "Bird dog", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Strekk motsatt arm og ben uten bevegelse i korsrygg." },
  { id: "e146", name: "Mountain climber sakte", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Trekk knær frem med kontroll og stabil hofte." },
  { id: "e147", name: "TRX fallout", category: "Styrke", group: "Kjerne", equipment: "TRX", level: "Øvet", description: "Hold kroppen strak mens armene glir frem." },
  { id: "e148", name: "Enarms farmer hold", category: "Styrke", group: "Grepsstyrke", equipment: "Manual", level: "Nybegynner", description: "Stå stille med tung vekt og hold overkroppen rett." },
  { id: "e149", name: "Plate pinch hold", category: "Styrke", group: "Grepsstyrke", equipment: "Vektskive", level: "Nybegynner", description: "Klem vektskiver mellom fingrene over tid." },
  { id: "e150", name: "Sled push", category: "Styrke", group: "Bein", equipment: "Slede", level: "Litt øvet", description: "Skyv sleden med korte kraftfulle steg." },
  { id: "e151", name: "Battle rope waves", category: "Styrke", group: "Helkropp", equipment: "Battle rope", level: "Litt øvet", description: "Lag jevne bølger med stram kjerne." },
  { id: "e152", name: "Kettlebell swing", category: "Styrke", group: "Bakside kjede", equipment: "Kettlebell", level: "Litt øvet", description: "Eksplosiv hofteekstensjon med nøytral rygg." },
  { id: "e153", name: "Kettlebell clean", category: "Styrke", group: "Helkropp", equipment: "Kettlebell", level: "Øvet", description: "Trekk vekten tett og fang mykt i rack-posisjon." },
  { id: "e154", name: "Kettlebell snatch", category: "Styrke", group: "Helkropp", equipment: "Kettlebell", level: "Øvet", description: "Eksplosiv bane til over hodet med kontroll." },
  { id: "e155", name: "Thruster", category: "Styrke", group: "Helkropp", equipment: "Manualer", level: "Litt øvet", description: "Kombiner frontbøy og press i en flytende rep." },
  { id: "e156", name: "Wall ball", category: "Styrke", group: "Helkropp", equipment: "Medisinball", level: "Nybegynner", description: "Gå i dyp knebøy og kast kontrollert til mål." },
  { id: "e157", name: "Bear crawl", category: "Styrke", group: "Kjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Krabb med lav hofte og stabil overkropp." },
  { id: "e158", name: "Band pull-apart", category: "Styrke", group: "Øvre rygg", equipment: "Strikk", level: "Nybegynner", description: "Trekk strikken ut med skuldrene ned og bak." },
  { id: "e159", name: "Monster walk", category: "Styrke", group: "Sete", equipment: "Miniband", level: "Nybegynner", description: "Gå sideveis med stram miniband over knær." },
  { id: "e160", name: "Spanish squat", category: "Styrke", group: "Forside lår", equipment: "Strikk", level: "Litt øvet", description: "Len deg bakover i bånd og jobb dypt i knevinkel." },
  { id: "e161", name: "World's greatest stretch", category: "Uttøyning", group: "Hofte", equipment: "Kroppsvekt", level: "Nybegynner", description: "Kombiner utfall, rotasjon og hofteåpning i én sekvens." },
  { id: "e162", name: "90/90 hofte-rotasjon", category: "Uttøyning", group: "Hofte", equipment: "Kroppsvekt", level: "Nybegynner", description: "Bytt side kontrollert for bedre rotasjon i hofte." },
  { id: "e163", name: "Pigeon stretch", category: "Uttøyning", group: "Sete", equipment: "Kroppsvekt", level: "Nybegynner", description: "Len deg frem over fremre bein for setestrekk." },
  { id: "e164", name: "Lizard stretch", category: "Uttøyning", group: "Hofte", equipment: "Kroppsvekt", level: "Litt øvet", description: "Dyp utfallsposisjon med fokus på hoftebøyer." },
  { id: "e165", name: "Frog stretch", category: "Uttøyning", group: "Innside lår", equipment: "Kroppsvekt", level: "Litt øvet", description: "Senk hoften rolig bakover for adductor-strekk." },
  { id: "e166", name: "Couch stretch", category: "Uttøyning", group: "Forside lår", equipment: "Benk", level: "Litt øvet", description: "Knær nær vegg og hofte frem for dyp quad-strekk." },
  { id: "e167", name: "Sittende hamstring med strikk", category: "Uttøyning", group: "Bakside lår", equipment: "Strikk", level: "Nybegynner", description: "Trekk forsiktig i strikken og hold ryggen lang." },
  { id: "e168", name: "Dynamisk hamstring kick", category: "Uttøyning", group: "Bakside lår", equipment: "Kroppsvekt", level: "Nybegynner", description: "Kontrollerte benspark for bevegelighet i hofte." },
  { id: "e169", name: "Ankelmobilitet kne-til-vegg", category: "Uttøyning", group: "Ankel", equipment: "Vegg", level: "Nybegynner", description: "Før kneet mot vegg uten at hælen løfter seg." },
  { id: "e170", name: "Dorsalfleksjon stretch", category: "Uttøyning", group: "Ankel", equipment: "Strikk", level: "Litt øvet", description: "Bruk strikk for ekstra trekk i ankelleddet." },
  { id: "e171", name: "Soleus stretch", category: "Uttøyning", group: "Legg", equipment: "Vegg", level: "Nybegynner", description: "Bøy kneet lett for å treffe soleus." },
  { id: "e172", name: "Peroneal stretch", category: "Uttøyning", group: "Legg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Roter foten kontrollert for utside legg/fot." },
  { id: "e173", name: "Brystrygg over foam roller", category: "Uttøyning", group: "Brystrygg", equipment: "Foam roller", level: "Nybegynner", description: "Rull rolig og åpne brystkassen over rullen." },
  { id: "e174", name: "Open book rotasjon", category: "Uttøyning", group: "Brystrygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Roter overkroppen sideveis med kontrollert pust." },
  { id: "e175", name: "Thread the needle", category: "Uttøyning", group: "Brystrygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Før armen under kroppen og kjenn strekk i rygg/skulder." },
  { id: "e176", name: "Lat stretch i dørkarm", category: "Uttøyning", group: "Rygg", equipment: "Dørkarm", level: "Nybegynner", description: "Len hoften bak for å åpne siden av ryggen." },
  { id: "e177", name: "Wall angels", category: "Uttøyning", group: "Skuldre", equipment: "Vegg", level: "Nybegynner", description: "Hold kontakt med veggen gjennom bevegelsen." },
  { id: "e178", name: "Sleeper stretch", category: "Uttøyning", group: "Skuldre", equipment: "Kroppsvekt", level: "Litt øvet", description: "Roter skulderen forsiktig innover i sideliggende." },
  { id: "e179", name: "Bånddislokasjoner", category: "Uttøyning", group: "Skuldre", equipment: "Strikk", level: "Nybegynner", description: "Før armene over hodet i kontrollert tempo." },
  { id: "e180", name: "Pec minor stretch", category: "Uttøyning", group: "Bryst", equipment: "Vegg", level: "Nybegynner", description: "Plasser armen høyt og roter kroppen bort." },
  { id: "e181", name: "Biceps stretch mot vegg", category: "Uttøyning", group: "Biceps", equipment: "Vegg", level: "Nybegynner", description: "Strekk armen bakover med håndflate ut." },
  { id: "e182", name: "Underarmsstrekk fleksor", category: "Uttøyning", group: "Underarm", equipment: "Kroppsvekt", level: "Nybegynner", description: "Trekk fingrene bakover med strake albuer." },
  { id: "e183", name: "Underarmsstrekk ekstensor", category: "Uttøyning", group: "Underarm", equipment: "Kroppsvekt", level: "Nybegynner", description: "Bøy håndleddet ned og hold lett press." },
  { id: "e184", name: "Håndledd sirkler", category: "Uttøyning", group: "Håndledd", equipment: "Kroppsvekt", level: "Nybegynner", description: "Roter håndleddene rolig begge retninger." },
  { id: "e185", name: "Knestående ryggstrekk", category: "Uttøyning", group: "Rygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "Sitt bak på hælene og strekk armene frem." },
  { id: "e186", name: "Supine spinal twist", category: "Uttøyning", group: "Rygg", equipment: "Kroppsvekt", level: "Nybegynner", description: "La knær falle sideveis med skuldre i gulvet." },
  { id: "e187", name: "Happy baby", category: "Uttøyning", group: "Hofte", equipment: "Kroppsvekt", level: "Nybegynner", description: "Trekk knær mot armhuler og hold korsrygg avslappet." },
  { id: "e188", name: "Adductor rockback", category: "Uttøyning", group: "Innside lår", equipment: "Kroppsvekt", level: "Nybegynner", description: "Skyv hoften bakover med ett bein strakt ut." },
  { id: "e189", name: "Copenhagen stretch", category: "Uttøyning", group: "Innside lår", equipment: "Benk", level: "Litt øvet", description: "Strekk adduktor med beinet støttet på benk." },
  { id: "e190", name: "Glute med stretch", category: "Uttøyning", group: "Sete", equipment: "Kroppsvekt", level: "Nybegynner", description: "Kryss ben over og trekk forsiktig mot deg." },
  { id: "e191", name: "Neck side stretch", category: "Uttøyning", group: "Nakke", equipment: "Kroppsvekt", level: "Nybegynner", description: "Trekk hodet rolig til siden uten å løfte skulder." },
  { id: "e192", name: "Neck rotation stretch", category: "Uttøyning", group: "Nakke", equipment: "Kroppsvekt", level: "Nybegynner", description: "Roter hodet sakte side til side i smertefri bane." },
  { id: "e193", name: "Standing side bend stretch", category: "Uttøyning", group: "Sidekjerne", equipment: "Kroppsvekt", level: "Nybegynner", description: "Len overkroppen sideveis og hold hoften stabil." },
  { id: "e194", name: "QL stretch på benk", category: "Uttøyning", group: "Korsrygg", equipment: "Benk", level: "Nybegynner", description: "Løft arm over hodet og strekk siden av korsryggen." },
  { id: "e195", name: "Pust + diafragma mobilitet", category: "Uttøyning", group: "Mobilitet", equipment: "Kroppsvekt", level: "Nybegynner", description: "Rolig nasal pust med fokus på ekspansjon i ribben." },
];

const initialPrograms: TrainingProgram[] = [
  {
    id: "p1",
    memberId: "m1",
    title: "Helkropp 2 dager i uka",
    goal: "Bygge grunnstyrke",
    notes: "Start rolig og fokuser på teknikk.",
    createdAt: formatDateDdMmYyyy(new Date()),
    exercises: [
      { id: "pe1", exerciseId: "e1", exerciseName: "Knebøy", sets: "3", reps: "8", weight: "40", restSeconds: "120", notes: "Kontrollert tempo" },
      { id: "pe2", exerciseId: "e3", exerciseName: "Nedtrekk", sets: "3", reps: "10", weight: "35", restSeconds: "75", notes: "Trekk til bryst" },
    ],
  },
];

const initialLogs: WorkoutLog[] = [
  {
    id: "l1",
    memberId: "m1",
    programTitle: "Helkropp 2 dager i uka",
    date: formatDateDdMmYyyy(new Date()),
    status: "Fullført",
    note: "Fin økt.",
  },
];

const initialMessages: ChatMessage[] = [
  { id: "c1", memberId: "m1", sender: "trainer", text: "Husk rolig start denne uka.", createdAt: formatDateDdMmYyyy(new Date()) },
  { id: "c2", memberId: "m1", sender: "member", text: "Supert, jeg logger økten i kveld.", createdAt: formatDateDdMmYyyy(new Date()) },
  { id: "c3", memberId: "m2", sender: "member", text: "Kan du se over ukeplanen min?", createdAt: formatDateDdMmYyyy(new Date()) },
];

export function getDefaultState(): AppState {
  return {
    workoutMode: null,
    workoutCelebration: null,
    members: initialMembers,
    exercises: initialExercises,
    programs: initialPrograms,
    logs: initialLogs,
    messages: initialMessages,
    currentUser: null,
    role: "trainer",
    selectedMemberId: initialMembers[0]?.id ?? "",
    memberViewId: initialMembers[0]?.id ?? "",
  };
}
