-- Vanlige styrkeøvelser med norske navn (idempotent).
-- Kjør: npx supabase db query --linked -f src/supabase/seed_strength_exercises_no.sql

insert into public.exercise_bank (id, name, category, muscle_group, equipment, level, description, is_active)
values
  ('e201', 'Utfall forover', 'Styrke', 'Bein', 'Manualer', 'Nybegynner', 'Ta et langt steg frem, senk kneet til ca. 90° og press opp gjennom hælen.', true),
  ('e202', 'Benkpress med manualer', 'Styrke', 'Bryst', 'Manualer', 'Nybegynner', 'Press manualene i jevn bue, hold skuldrene stabile og kontroller senkefase.', true),
  ('e203', 'Skrå benkpress', 'Styrke', 'Bryst', 'Stang', 'Litt øvet', 'Skrå benk 30–45°, stangen mot øvre bryst med kontrollert bane.', true),
  ('e204', 'Roing med stang', 'Styrke', 'Rygg', 'Stang', 'Litt øvet', 'Len frem med flat rygg, trekk stangen mot navlen og klem skulderbladene.', true),
  ('e205', 'Magebøy', 'Styrke', 'Kjerne', 'Kroppsvekt', 'Nybegynner', 'Ligg på ryggen, curl overkroppen opp og senk kontrollert uten å rive i nakken.', true),
  ('e206', 'Sittende magebøy', 'Styrke', 'Kjerne', 'Kroppsvekt', 'Nybegynner', 'Sitt med føttene i gulvet, curl brystet mot knærne med rolig tempo.', true),
  ('e207', 'Rygghev i maskin', 'Styrke', 'Rygg', 'Maskin', 'Nybegynner', 'Løft overkroppen med hoften som hengsel, unngå å hyperextendere korsryggen.', true),
  ('e208', 'Multipress skuldre', 'Styrke', 'Skuldre', 'Maskin', 'Nybegynner', 'Press jevnt opp uten å svaie korsryggen, full strekk uten smerte i skulder.', true),
  ('e209', 'Underhåndstrekk', 'Styrke', 'Rygg', 'Kroppsvekt', 'Litt øvet', 'Grepet med håndflatene mot deg, trekk brystet opp til stangen.', true),
  ('e210', 'Flyes med manualer', 'Styrke', 'Bryst', 'Manualer', 'Nybegynner', 'Myke albuer, senk manualene til siden og klem brystet sammen i topp.', true),
  ('e211', 'Fronthev', 'Styrke', 'Skuldre', 'Manualer', 'Nybegynner', 'Løft manualene foran kroppen til skulderhøyde uten sving i overkroppen.', true),
  ('e212', 'Tricepspress i maskin', 'Styrke', 'Triceps', 'Maskin', 'Nybegynner', 'Hold overarmene stabile mot putene og press ut til full strekk.', true),
  ('e213', 'Bicepscurl i maskin', 'Styrke', 'Biceps', 'Maskin', 'Nybegynner', 'Følg maskinens bane, albuer tett og kontrollert senkefase.', true),
  ('e214', 'Kabel crossover', 'Styrke', 'Bryst', 'Kabel', 'Nybegynner', 'Litt fremoverlent, klem brystet sammen foran kroppen med myke albuer.', true),
  ('e215', 'Knebøy med manualer', 'Styrke', 'Bein', 'Manualer', 'Nybegynner', 'Hold manualene ved sidene eller ved skuldrene, knær ut i linje med tærne.', true),
  ('e216', 'Utfall med stang', 'Styrke', 'Bein', 'Stang', 'Litt øvet', 'Stangen på øvre rygg, ta kontrollerte steg og hold overkroppen oppreist.', true),
  ('e217', 'Bulgarsk splittbøy', 'Styrke', 'Bein', 'Manualer', 'Litt øvet', 'Bakre fot på benk, senk dypt i fremre bein og press opp med stabil hofte.', true),
  ('e218', 'Armhevinger', 'Styrke', 'Bryst', 'Kroppsvekt', 'Nybegynner', 'Kroppen i rett linje fra hode til hæl, albuer ca. 45° fra siden.', true),
  ('e219', 'Hoftebøy med manual', 'Styrke', 'Sete', 'Manual', 'Nybegynner', 'Manual over hoften, press opp og klem setet hardt i topp uten svai i rygg.', true),
  ('e220', 'Assistert underhåndstrekk', 'Styrke', 'Rygg', 'Maskin', 'Nybegynner', 'Velg passende motstand, trekk brystet mot stangen med kontrollert senk.', true),
  ('e221', 'Assisterte dips', 'Styrke', 'Bryst/Triceps', 'Maskin', 'Nybegynner', 'Litt framoverlent bryst, senk kontrollert og press opp uten å låse albuene.', true),
  ('e222', 'Hyperextension', 'Styrke', 'Bakside lår', 'Kroppsvekt', 'Nybegynner', 'Løft overkroppen med hoften, ikke ved å bøye ryggen.', true),
  ('e223', 'Sissy squat', 'Styrke', 'Forside lår', 'Kroppsvekt', 'Litt øvet', 'Hold hælene ned, len deg bakover og reis deg med kontrollert kneekontroll.', true),
  ('e224', 'Trap bar markløft', 'Styrke', 'Bakside kjede', 'Trap bar', 'Litt øvet', 'Stå midt i stangen, press føttene i gulvet og løft med nøytral rygg.', true),
  ('e225', 'Shrugs med stang', 'Styrke', 'Øvre rygg', 'Stang', 'Nybegynner', 'Løft skuldrene rett opp mot ørene, hold kort stopp og senk rolig.', true),
  ('e226', 'Stående roing med stang', 'Styrke', 'Rygg', 'Stang', 'Litt øvet', 'Kneene lett bøyd, trekk stangen mot magen med albuer tett inn.', true),
  ('e227', 'Stående skulderpress', 'Styrke', 'Skuldre', 'Stang', 'Litt øvet', 'Spenn kjernen, press stangen rett over hodet uten å svaie.', true),
  ('e228', 'Pullover med stang', 'Styrke', 'Bryst/Rygg', 'Stang', 'Litt øvet', 'Senk stangen kontrollert bak hodet og trekk tilbake over brystet.', true),
  ('e229', 'Sidehev i kabel', 'Styrke', 'Skuldre', 'Kabel', 'Nybegynner', 'Løft armen til siden med lett bøy i albuen, unngå sving i overkroppen.', true),
  ('e230', 'Nedtrekk underhånd', 'Styrke', 'Rygg', 'Kabel', 'Nybegynner', 'Underhåndsgrep, trekk stangen mot øvre bryst og klem skulderbladene.', true),
  ('e231', 'Liggende benkpress', 'Styrke', 'Bryst', 'Manualer', 'Nybegynner', 'Ligg flat, press manualene opp og sammen uten å miste skulderkontakt med benken.', true),
  ('e232', 'Utfall til siden', 'Styrke', 'Innside lår', 'Manual', 'Nybegynner', 'Stort steg til siden, hold foten flat og press tilbake til start.', true),
  ('e233', 'Enarms nedtrekk', 'Styrke', 'Rygg', 'Kabel', 'Nybegynner', 'Trekk håndtaket ned mot siden av brystet med kontrollert rotasjon i overkroppen.', true),
  ('e234', 'Stangcurl', 'Styrke', 'Biceps', 'Stang', 'Nybegynner', 'Albuer stabile ved siden, curl opp uten å svinge overkroppen.', true),
  ('e235', 'Franskpress liggende', 'Styrke', 'Triceps', 'EZ-stang', 'Litt øvet', 'Ligg på benk, senk stangen mot pannen med faste albuer og press opp.', true)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  level = excluded.level,
  description = excluded.description,
  is_active = true,
  updated_at = now();
